### ISSUE TITLE
Setting up track1/track2 environments fails on OSX and Linux

### ISSUE THREAD

**Issue by orasanen** [bootphon/zerospeech2017#11]
In order to participate to ZS2020, I tried to set up the environments for track1 and track 2 evaluations, but the conda package specifications seem outdated (?):

--------------------------------
This is on Linux:

./track1/setup/setup_track1.sh
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - wheel==0.29.0=py27_0
  - setuptools==27.2.0=py27_0
  - cython==0.24.1=py27_0
  - h5py==2.6.0=np111py27_2
  - python==2.7.12=1
  - tk==8.5.18=0
  - readline==6.2=2
  - mkl==11.3.3=0
  - pandas==0.19.1
  - six==1.10.0=py27_0
  - scipy==0.18.1=np111py27_0
  - zlib==1.2.8=3
  - numpy==1.11.2=py27_0
  - sqlite==3.13.0=0
  - hdf5==1.8.17=1
  - openssl==1.0.2j=0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Error: cannot install from requirements_conda.txt

----

 ./track2/setup/setup_track2.sh
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - zlib==1.2.8=3
  - openssl==1.0.2j=0
  - sqlite==3.13.0=0
  - numpy==1.11.3=py27_0
  - libgfortran==3.0.0=1
  - hdf5==1.8.17=1
  - python==2.7.12=1
  - h5py==2.6.0=np111py27_2
  - pandas==0.19.2=np111py27_0
  - tk==8.5.18=0
  - setuptools==27.2.0=py27_0
  - six==1.10.0=py27_0
  - scipy==0.18.1=np111py27_1
  - pep8==1.7.0=py27_0
  - mkl==2017.0.1=0
  - pyflakes==1.4.0=py27_0
  - flake8==2.5.1=py27_0
  - readline==6.2=2
  - cython==0.25.2=py27_0
  - joblib==0.9.4=py27_0
  - python-dateutil==2.6.0=py27_0
  - wheel==0.29.0=py27_0
  - pip==8.1.2=py27_0
  - mccabe==0.3.1=py27_0
  - pytz==2016.10=py27_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Error: cannot install from requirements_conda.txt

--------------------------------
This is on OSX 

./track1/setup/setup_track1.sh
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - setuptools==27.2.0
  - mkl==11.3.3
  - openssl==1.0.2j
  - zlib==1.2.8
  - tk==8.5.18
  - h5py==2.6
  - numpy==1.11.2
  - python==2.7.12
  - hdf5==1.8.17
  - scipy==0.18.1
  - cython==0.24.1
  - pandas==0.19.1
  - sqlite==3.13.0
  - readline==6.2

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Error: cannot install from requirements_conda.txt

./track2/setup/setup_track2.sh

Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyflakes==1.4.0=py27_0
  - six==1.10.0=py27_0
  - joblib==0.9.4=py27_0
  - flake8==2.5.1=py27_0
  - hdf5==1.8.17=1
  - setuptools==27.2.0=py27_0
  - wheel==0.29.0=py27_0
  - mccabe==0.3.1=py27_0
  - pytz==2016.10=py27_0
  - cython==0.25.2=py27_0
  - mkl==2017.0.1=0
  - python-dateutil==2.6.0=py27_0
  - sqlite==3.13.0=0
  - python==2.7.12=1
  - pandas==0.19.2=np111py27_0
  - readline==6.2=2
  - pep8==1.7.0=py27_0
  - scipy==0.18.1=np111py27_1
  - libgfortran==3.0.0=1
  - tk==8.5.18=0
  - zlib==1.2.8=3
  - h5py==2.6.0=np111py27_2
  - openssl==1.0.2j=0
  - pip==8.1.2=py27_0
  - numpy==1.11.3=py27_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Error: cannot install from requirements_conda.txt

**Comment by mmmaat** [comment]
Indeed as python2 is out of date a lot of dependencies are missing.

But we are publishing a dedicated package for the 2020 challenge : https://github.com/bootphon/zerospeech2020. Please use that. And if you can wait few hours we are actually fixing the very details before the release. As well https://zerospeech.com/2020 will be released in few hours with all the details.

Thanks!

**Comment by orasanen** [comment]
Cheers, thanks!
