### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by rajathkmp** [bootphon/zerospeech2017#5]
Does the recent commits in setup_track2.sh affect the baseline results in anyway?

I had setup track2 with the old files long ago and had run the baseline systems.

Should I reconfigure and re-run?

**Comment by jubenjum** [comment]
During last week I have been changing the installation on procedure of compiling feacalc, these modifications won't change the results of the baseline, then there is no need to re-run the that part of the challenge.

Juan
