### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Cel1ne** [bootphon/zerospeech2017#6]
After complete installation, when testing we get the following output:

$ pytest ./track1/src
python: can't open file 'test.py': [Errno 2] No such file or directory

any hint?

**Comment by mmmaat** [comment]
Hello @Cel1ne  !

I just tried the operation on a fresh installation and the tests are OK for me.

Did you clone the repository with the --recursive option? 
Did you activate your **zerospeech** virtual environment as explained in the README?
What give you the command "which pytest" ? "which python" ?

Thanks,
Mathieu

**Comment by Cel1ne** [comment]
Hello and thanks for the answer.

I download zip because when i want to clone i have :
```
$ git clone --recursive git@github.com:bootphon/zerospeech2017.git
Clonage dans 'zerospeech2017'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

"which pytest"  -->` /home/[name]/anaconda2/bin/pytest`
 "which python" -->`/home/[name]/anaconda2/bin/python`

**Comment by mmmaat** [comment]
Ok I see, this is because you cloned it using ssh...
Can you try to clone it using https ? It should work.

     git clone --recursive https://github.com/bootphon/zerospeech2017.git

**Comment by Cel1ne** [comment]
Ok, thanks !
